@startuml

package "Как создаётся веб-сайт" {

    component "У вас рождается идея сделать сайт" as idea

    component "Вы ищете дизайнера, верстальщика, программиста и системного администратора" as hr

    component spec [
        Вы описываете идею в виде технического задания.
        Техническое задание - это текстовое описание вашей идеи.

        Для каждого человека отдельное ТЗ:

        - **Дизайнер**: что посетители смогут делать на сайте

        - **Верстальщик**: с каких устройств (ПК, мобильное приложение) и программ
        (Chrome, Firefox, Safari, мобильные браузеры и их версии) можно будет зайти на сайт

        - **Программист**: на каких технологиях (язык программирования, база данных)
        должен быть сделан сайт, постраничное описание функционала сайта

        - **Системный администратор**: где должен быть размещен сайт (хостинг,
        выделенный или виртуальный сервер), на каком оборудовании (характеристики сервера)
        и при обращении с какого домена можно будет зайти на сайт
    ]

    component designing [
        Этап №1.

        Дизайнер создаёт **макеты** сайта - рисует функционал того, что
        посетители могут делать на сайте.
    ]

    component html [
        Этап №2.

        Верстальщик создаёт **HTML/CSS/JS** файлы из **макетов** - верстает сайт, чтобы
        отображение было корректным на указанных устройствах и программах.
    ]

    component coding [
        Этап №3.

        Программист создаёт **код** сайта из **HTML/CSS/JS** файлов - программирует сайт, чтобы
        функциональность работала, как было задумано.
    ]

    component sysadmin [
        Этап №4.

        Системный администратор получает **код** сайта, **доступ к хостингу/серверу**, доступ к управлению
        **DNS** вашего **домена** и устанавливает сайт, налаживает его работу, чтобы даже
        при перезагрузке сервера сайт работал корректно.

        Также системный администратор может настроить отправку электронных сообщений, бекапы базы данных.
    ]

    idea --|> hr
    hr --|> spec
    spec --|> designing
    designing --|> html
    html --|> coding
    coding --|> sysadmin

    package "Что у вас должно быть" {
        component things #eeeeee [
            - Домен
            - Хостинг, выделенный или виртуальный сервер
        ]
    }

}

@enduml
